### ISSUE TITLE
iPhone 6 Plus 64GB

### ISSUE THREAD

**Issue by TaiTair** [iabem97/saigon#55]
## Two different errors  

I think one is a kernel panic causing the phone to reboot

[1.log](https://github.com/iabem97/saigon/files/1377360/1.log)

The other looks like a failed privilege escalation

[2.log](https://github.com/iabem97/saigon/files/1377365/2.log)

Let me know if anything else is needed.

Cheers.

**Comment by xnuos** [comment]
@TaiTair: **PLEASE** First be sure to **check** the _**other Issues**_ carefully to see if your error logs have a similar error to the ones mentioned. (As they most likely do.) Then, please do _one_ of the two things below:

_**A.)** **If you find your issue:**_ 

**DO NOT POST IT OR SOMETHING LIKE THIS AGAIN!** I cannot stress the importance of this as it is part of the reason developers are driven from the public. It is irritating and only shows how little people regard the time of others. While this may be _your_ issue, it is the same for everyone else and posting this is not helpful, it just screams: 

> "I dont care to look at others peoples issues to see if there is something similar, I only care about **ME** and **MY** role in helping this work for **ME**."

 
That's not help, that's hindrance.

**_B.)_** **_If you do not find your issue:_**
Please post here as this is the **true purpose** of this section. Please title it according to the error received and provide logs from the debug. If he has the time or any information to provide you (or requires of you), he will let you know or ask, otherwise, you must patiently wait for a fix.

**Please close this Issue.**

**Comment by TaiTair** [comment]
Buddy - I was trying to provide logs and be helpful. If you're gonna bitch about it well have fun with your damn software. You're welcome by the way.

Being a developer myself I would've helped you. But with the kind of answer you gave me I'm not going to bother. Peace out.

Close it yourself.
