### ISSUE TITLE
iPhone 6 iOS 10.2.1 JB Error

### ISSUE THREAD

**Issue by koflerm** [iabem97/saigon#63]
Here is my log. Think it took about 5 minutes to come past triple_fetch but failed later on. Here is my log I hope I cloud help.

Log:
https://pastebin.com/nCX6tuYg
(Shortened the memory output because of the pastern max size xD)

**Comment by xnuos** [comment]
@koflerm: **PLEASE** First be sure to **check** the _**other Issues**_ carefully to see if your error logs have a similar error to the ones mentioned. (As they do.) Then, please do _one_ of the two things below:

_**A.)** **If you find your issue:**_ 

**DO NOT POST IT OR SOMETHING LIKE THIS AGAIN!** I cannot stress the importance of this as it is part of the reason developers are driven from the public. It is irritating and only shows how little people regard the time of others. While this may be _your_ issue, it is the same for everyone else and posting this is not helpful, it just screams: 

> "I dont care to look at others peoples issues to see if there is something similar, I only care about **ME** and **MY** role in helping this work for **ME**."

 
That's not help, that's hindrance.

**_B.)_** **_If you do not find your issue:_**
Please post here as this is the **true purpose** of this section. Please title it according to the error received and provide logs from the debug. If he has the time or any information to provide you (or requires of you), he will let you know or ask, otherwise, you must patiently wait for a fix.

**Please close this Issue.**
