### ISSUE TITLE
Kernel panic on iPhone SE Samsung Apple A9 with the beta .ipa

### ISSUE THREAD

**Issue by billcipherog** [iabem97/saigon#70]
Device kernel panics everytime immediately when it reaches "privilege escalation...".
I would really appreciate your help, though I'm already grateful for all the work you put in this jailbreak.

**Comment by Archangel04** [comment]
Same here. It is the only error which happens.
 Escaping sandbox is almost non existent but it immediately crashes on Privilege Escalation.

**Comment by xnuos** [comment]
@billcipherog: First be sure to **check** the _**other Issues**_ carefully to see if your error logs have a similar error to the ones mentioned. (As this has been mentioned 25+ times and the error log is literally in English.) Then, please do _one_ of the two things below:

_**A.)** **If you find your issue:**_ 

**DO NOT POST IT OR SOMETHING LIKE THIS AGAIN!** I cannot stress the importance of this as it is part of the reason developers are driven from the public. It is irritating and only shows how little people regard the time of others. While this may be _your_ issue, it is the same for everyone else and posting this is not helpful, it just screams: 

> "I dont have the care to look at others reports to see if there is something similar, I only care about **ME** and **MY** role in helping this work for **ME**."

 
That's not help, that's hindrance.

**_B.)_** **_If you do not find your issue:_**
Please post here as this is the **true purpose** of this section. Please title it according to the error received and provide logs from the debug. If he has the time or any information to provide you (or requires of you), he will let you know or ask, otherwise, you must patiently wait for a fix.

**Please close this Issue.**
