### ISSUE TITLE
iPhone 7/Plus 10.2.1 manual override

### ISSUE THREAD

**Issue by jigsaw294** [iabem97/saigon#72]
Hey Abraham, do you think you could add a manual override into the .ipa to run the exploit on unsupported devices? (iPhone 7/Plus on 10.2.1)

Maybe have a warning pop up that steers you away from the responsibility over the owners device.

**Comment by xnuos** [comment]
@iy005: This is an **Issues** section. Not a _forum_. Please do not treat it as such. This is not the place you should be educating yourself, or I to have this discussion with you. 

Simply, and I beg of you: **close this issue** after I explain this...

There is no "manual override" and I do not know which hacker movie you just viewed, but causing a chain of exploits in Obj-C that require offsets to function (offsets being, in simple terms, where to direct the exploit for specific devices) and the fact there is modules of protection on the kernel of the iPhone 7/Plus (**that has not been bypassed in this exploit** and require time to implement various workarounds), cannot simply be overridden. The fix must be _written_ into the project. That takes _time_ and the _Issues_ section is **not** where you ask questions like this, or for updates.   

_There is a reason your device isn't supported._ (I.e. Because it wouldn't work. Thus causing you to misuse the **Issues** section as you already have done, trying to figure out why it never works.)

Also, who makes you think the developer has responsibility over the device? Lmao I can write something that attempts to brick it and if you came to me complaining, I could literally electronically flip you off and you can't do shit. Yeah, I mean it. 
You run the risk of running this software, and as such, are responsible for the outcome, not the developer. Please remember that in the future.

**Now, please close this Issue.**

**Comment by jigsaw294** [comment]
lol I am gonna assume that you are not an actual asshole in real life, you just having/had a shitty day.

I am all familiar with open source development since I have been using Android devices in the past, ALOT. 
I KNOW that the developer has not responsibility over the owners device, I only suggested that for the sake of the illiterates that might come whining when their iPhone 7 turns into paperweight.
Anyways, out.

**Comment by jigsaw294** [comment]
oops, opened again >_> 

Will close at Abrahams request.

**Comment by jigsaw294** [comment]
Updated to iOS 11.2 lol
