### ISSUE TITLE
Iphone 6s+ doesnt work

### ISSUE THREAD

**Issue by iy005** [iabem97/saigon#74]
as of now. anyone know when it will work., and why is the 6s supported but not 6s+

**Comment by xnuos** [comment]
@iy005: This is an **Issues** section. Not a _forum_. Please do not treat it as such, and respectfully message the developer on the status of his work. (Or, ya know, check the "commits") If he has the time or any information to provide you, he will, otherwise, you unequivocally have your answer. (I.e. There is nothing to update or no progress made.)

Also, personally I do not know. However, _if I cared to know_, I would _analyze the code_ and _**Google**_ _what I do not understand_ to make sense of it. If this doesn't interest you, as anyone has the ability to learn, then you may deliver your inquiry to the developer. If he has the time, you may receive an answer, otherwise, the former is your only option. If option _A._ or option _B._ doesn't sound enticing enough for you, simply don't ask the question, especially in an **Issues** section.

**Please close this Issue.**

**Comment by xka1** [comment]
try to do so

1) install zJailbreak http://pangu8.com/jailbreak/10.2/
2) open
 install a beta ota blocker (tvOS beta software profile)
3) remove
zJailbreak
4) restart the device (power + home buton)
5) open saigon Beta 2r1
Option to reinstall Cydia by
holding 'jailbreak' button then tapping it again
