### ISSUE TITLE
Iphone 6+ Stuck at Escaping Sandbox

### ISSUE THREAD

**Issue by pop4571** [iabem97/saigon#75]
So I've jailbroken successfully on my iPhone 6+ running iOS 10.2.1, the problem came afterwards, whilst installing some tweaks i had to reboot and my phone black screened non responsive so i hard reset it(power and home button until apple logo) and its just stuck at escaping sandbox and I've left the phone on for around 15+ minutes now and yet no prevail. Anyone else having this issue/know a solution.

**Comment by T1V0h** [comment]
dam that sucks

**Comment by ar0ck86** [comment]
Try to diasable Find My iPhone (or sign out of iCloud). Turn on Airplane Mode. Close all open apps and open Saigon. Wait around 10 seconds then try to 'Jailbreak'. It still takes multiple tries but it seems to help. DO NOT INSTALL APPSYNC right now and I would advise waiting for more testing before going crazy with Substrate.

**Comment by jakeajames** [comment]
reboot and try again. If sandbox bypass doesn't work within 2-5 minutes, it just will never work

**Comment by xnuos** [comment]
To @pop4571: Please **close this issue** and **research** your topics of issue in the future. This is not a current issue at hand with this jailbreak and only clutters the Issues section up. This will happen, so just keep trying. For some it may take up to 10 tries...others 200+. Just let the developer, who is already aware of this, work on the issue.

P.S. FYI: In simple terms, the "escape sandbox" exploit only works some of the time. If you would like to know why, please google it. 

**Please close this issue.**

Also, @jakeajames _"it just will never work"_ is simply not true. If you would like to state your reasoning as to why you say this, please do so, or be explicit in saying _"it will never work unless you reboot and try again,"_ as this may be misleading info to ill-informed users. Otherwise, please contact Ian Beer and explain to him as to why it _"will never work"_ on the [bugs.chromium.org](https://bugs.chromium.org/p/project-zero/issues/detail?id=1247) issues instead.

**Comment by xka1** [comment]
try to do so

1) install zJailbreak http://pangu8.com/jailbreak/10.2/
2) open
 install a beta ota blocker (tvOS beta software profile)
3) remove
zJailbreak
4) restart the device (power + home buton)
5) open saigon Beta 2r1
Option to reinstall Cydia by
holding 'jailbreak' button then tapping it again
