### ISSUE TITLE
iPod Touch 6 iOS 10.3?

### ISSUE THREAD

**Issue by TheForgottenKing** [iabem97/saigon#76]
What is the status on iOS 10.3(.1) as it requires KPPless. What could I do to help the process?

**Comment by xnuos** [comment]
@TheForgottenKing If you have expertise in Obj-C and can assist with debugging, error handling, etc. then please provide your assistance on the encoding frames issue by forking it, and working on the project in your own repository. If you do not have any knowledge of the aforementioned, simply put, you cannot help and effectively adding to the problem by posting this under _Issues._

Secondly, this is an **Issues** section. Not a _forum_. Please do not treat it as such, and respectfully message the developer on the status of his work. (Or, ya know, check the "commits")  If he has the time or any information to provide you, he will, otherwise, you unequivocally have your answer.  (I.e. There is nothing to update or no progress made.)

**Please close this issue.**
